version: "3.3"

services:
  app:
    image: swarmpit/swarmpit:1.6
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik-net
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.protocol=http
        - traefik.docker.network=traefik-net
        - traefik.frontend.rule=Host:${DOMAIN}
        - traefik.webservice.frontend.entryPoints=https
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https

  agent:
    image: swarmpit/agent:2.0
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net

networks:
  net:
    driver: overlay
    attachable: true
  traefik-net:
    external: true

volumes:
  db-data:
    driver: local
